# Site settings
title: Oka bRionZ
email: me@okabrionz.com
description: > # this means to ignore newlines until "baseurl:"
  Try to build site using Jekyll and it was awesome without themes right now.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: okabrionz
github_username:  okabrionz

# Build settings
markdown: kramdown
